---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-debian-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  - name: debian-container
    image: debian
    command: ["/bin/sh", "-c"]
    args: ["while true; do date >> /html/index.html; sleep 1; done"]
    volumeMounts:
    - name: html-volume
      mountPath: /html
  volumes:
  - name: html-volume
    emptyDir: {}
