---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  containers:
  - name: kuard-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 3
      successThreshold: 1
